[build]
builder = "nixpacks"

[deploy]
startCommand = "node autonomous-agent.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "web"

[services.variables]
NODE_ENV = "production"
PORT = "8080"